apiVersion: v1
kind: Service
metadata:
  # name of the service should be same as what other application is looking for
  # since worker app is looking for service named DB
  name: voting-service
  labels:
    name: my-pv-service

spec:
  # since this is front facing service and default service is with ClusterIP
  # so the type of the service should be changed to LB or NodePort
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
# link service to a particular POD
  selector:
    name: task-pv-pod